docs_dir: documentations/
extra:
  analytics:
    property: G-3WKZMNM34S
    provider: google
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us to make our documentation better.
extra_css:
  - stylesheets/extra.css
nav:
  - SQLSimple: index.md
  - Contributing: contributing.md
  - Help: help.md
  - Release: release.md
repo_name: bernardocouto/sqlsimple
repo_url: https://github.com/bernardocouto/sqlsimple
site_description: SQLSimple framework, easy to learn, fast to code, ready for production.
site_name: SQLSimple
site_url: https://sqlsimple.bernardocouto.com
theme:
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    scheme: sqlsimple
  name: material
